### PR TITLE
fix: actions overlay blocking video controls

### PR DESCRIPTION
**Pull request by mdomarus**
This fix aligns the Action wrapper to the top, hence it stops blocking video controls.

https://github.com/fbaiodias/react-video-recorder/issues/38

### CODE REVIEW

**Comment by niciqy** [comment]
When are we merging this change in? I am having the same issue as well

**Comment by shakeys** [comment]
Hello, any update to merge this fix? Need it badly.

**Comment by robertjwozniak** [comment]
@fbaiodias Is this going to be merged any time soon? It's a needed fix.

**Pull request merged**
